#   Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Please review and update values

workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 60
        instance_type: mac_mini_m1
        environment:
             node: 16.9.0
        scripts:
             - name: Install npm dependencies
               script: | 
                npm install
             - name: Build Android APK
               working_directory: android
               script: ./gradlew assembleRelease
        artifacts:
            - app/build/outputs/**/*.apk
            
        publishing:
          email:
            recipients:
              - imdurgeshgupta@gmail.com
            notify:
              success: true     # To not receive a notification when a build succeeds
              failure: false    # To not receive a notification when a build fails
   